// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "magnifin/internal/app/model"
)

// UserService is an autogenerated mock type for the UserService type
type UserService struct {
	mock.Mock
}

type UserService_Expecter struct {
	mock *mock.Mock
}

func (_m *UserService) EXPECT() *UserService_Expecter {
	return &UserService_Expecter{mock: &_m.Mock}
}

// FromJWT provides a mock function with given fields: ctx, token
func (_m *UserService) FromJWT(ctx context.Context, token string) (*model.User, error) {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for FromJWT")
	}

	var r0 *model.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.User, error)); ok {
		return rf(ctx, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.User); ok {
		r0 = rf(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserService_FromJWT_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FromJWT'
type UserService_FromJWT_Call struct {
	*mock.Call
}

// FromJWT is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *UserService_Expecter) FromJWT(ctx interface{}, token interface{}) *UserService_FromJWT_Call {
	return &UserService_FromJWT_Call{Call: _e.mock.On("FromJWT", ctx, token)}
}

func (_c *UserService_FromJWT_Call) Run(run func(ctx context.Context, token string)) *UserService_FromJWT_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *UserService_FromJWT_Call) Return(_a0 *model.User, _a1 error) *UserService_FromJWT_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserService_FromJWT_Call) RunAndReturn(run func(context.Context, string) (*model.User, error)) *UserService_FromJWT_Call {
	_c.Call.Return(run)
	return _c
}

// NewUserService creates a new instance of UserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserService(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserService {
	mock := &UserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
