// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import (
	context "context"
	model "magnifin/internal/app/model"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

type Repository_Expecter struct {
	mock *mock.Mock
}

func (_m *Repository) EXPECT() *Repository_Expecter {
	return &Repository_Expecter{mock: &_m.Mock}
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *Repository) GetByID(ctx context.Context, id int32) (*model.Connector, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *model.Connector
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) (*model.Connector, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32) *model.Connector); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Connector)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type Repository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
func (_e *Repository_Expecter) GetByID(ctx interface{}, id interface{}) *Repository_GetByID_Call {
	return &Repository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *Repository_GetByID_Call) Run(run func(ctx context.Context, id int32)) *Repository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *Repository_GetByID_Call) Return(_a0 *model.Connector, _a1 error) *Repository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_GetByID_Call) RunAndReturn(run func(context.Context, int32) (*model.Connector, error)) *Repository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// LikeSearchByName provides a mock function with given fields: ctx, name
func (_m *Repository) LikeSearchByName(ctx context.Context, name string) ([]model.Connector, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for LikeSearchByName")
	}

	var r0 []model.Connector
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]model.Connector, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []model.Connector); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Connector)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_LikeSearchByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LikeSearchByName'
type Repository_LikeSearchByName_Call struct {
	*mock.Call
}

// LikeSearchByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *Repository_Expecter) LikeSearchByName(ctx interface{}, name interface{}) *Repository_LikeSearchByName_Call {
	return &Repository_LikeSearchByName_Call{Call: _e.mock.On("LikeSearchByName", ctx, name)}
}

func (_c *Repository_LikeSearchByName_Call) Run(run func(ctx context.Context, name string)) *Repository_LikeSearchByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Repository_LikeSearchByName_Call) Return(_a0 []model.Connector, _a1 error) *Repository_LikeSearchByName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_LikeSearchByName_Call) RunAndReturn(run func(context.Context, string) ([]model.Connector, error)) *Repository_LikeSearchByName_Call {
	_c.Call.Return(run)
	return _c
}

// SearchByName provides a mock function with given fields: ctx, name
func (_m *Repository) SearchByName(ctx context.Context, name string) ([]model.Connector, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for SearchByName")
	}

	var r0 []model.Connector
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]model.Connector, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []model.Connector); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Connector)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_SearchByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchByName'
type Repository_SearchByName_Call struct {
	*mock.Call
}

// SearchByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *Repository_Expecter) SearchByName(ctx interface{}, name interface{}) *Repository_SearchByName_Call {
	return &Repository_SearchByName_Call{Call: _e.mock.On("SearchByName", ctx, name)}
}

func (_c *Repository_SearchByName_Call) Run(run func(ctx context.Context, name string)) *Repository_SearchByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Repository_SearchByName_Call) Return(_a0 []model.Connector, _a1 error) *Repository_SearchByName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_SearchByName_Call) RunAndReturn(run func(context.Context, string) ([]model.Connector, error)) *Repository_SearchByName_Call {
	_c.Call.Return(run)
	return _c
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
