// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import (
	context "context"
	model "magnifin/internal/app/model"

	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

type Service_Expecter struct {
	mock *mock.Mock
}

func (_m *Service) EXPECT() *Service_Expecter {
	return &Service_Expecter{mock: &_m.Mock}
}

// ListProviders provides a mock function with given fields: ctx
func (_m *Service) ListProviders(ctx context.Context) ([]model.Provider, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListProviders")
	}

	var r0 []model.Provider
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]model.Provider, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []model.Provider); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Provider)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_ListProviders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListProviders'
type Service_ListProviders_Call struct {
	*mock.Call
}

// ListProviders is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Service_Expecter) ListProviders(ctx interface{}) *Service_ListProviders_Call {
	return &Service_ListProviders_Call{Call: _e.mock.On("ListProviders", ctx)}
}

func (_c *Service_ListProviders_Call) Run(run func(ctx context.Context)) *Service_ListProviders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Service_ListProviders_Call) Return(_a0 []model.Provider, _a1 error) *Service_ListProviders_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_ListProviders_Call) RunAndReturn(run func(context.Context) ([]model.Provider, error)) *Service_ListProviders_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateProvider provides a mock function with given fields: ctx, provider
func (_m *Service) UpdateProvider(ctx context.Context, provider model.Provider) (*model.Provider, error) {
	ret := _m.Called(ctx, provider)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProvider")
	}

	var r0 *model.Provider
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Provider) (*model.Provider, error)); ok {
		return rf(ctx, provider)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.Provider) *model.Provider); ok {
		r0 = rf(ctx, provider)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Provider)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.Provider) error); ok {
		r1 = rf(ctx, provider)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_UpdateProvider_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateProvider'
type Service_UpdateProvider_Call struct {
	*mock.Call
}

// UpdateProvider is a helper method to define mock.On call
//   - ctx context.Context
//   - provider model.Provider
func (_e *Service_Expecter) UpdateProvider(ctx interface{}, provider interface{}) *Service_UpdateProvider_Call {
	return &Service_UpdateProvider_Call{Call: _e.mock.On("UpdateProvider", ctx, provider)}
}

func (_c *Service_UpdateProvider_Call) Run(run func(ctx context.Context, provider model.Provider)) *Service_UpdateProvider_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.Provider))
	})
	return _c
}

func (_c *Service_UpdateProvider_Call) Return(_a0 *model.Provider, _a1 error) *Service_UpdateProvider_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_UpdateProvider_Call) RunAndReturn(run func(context.Context, model.Provider) (*model.Provider, error)) *Service_UpdateProvider_Call {
	_c.Call.Return(run)
	return _c
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
