// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import (
	context "context"
	model "magnifin/internal/app/model"

	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

type Service_Expecter struct {
	mock *mock.Mock
}

func (_m *Service) EXPECT() *Service_Expecter {
	return &Service_Expecter{mock: &_m.Mock}
}

// ListConnections provides a mock function with given fields: ctx, user
func (_m *Service) ListConnections(ctx context.Context, user *model.User) ([]model.ConnectionWithAccounts, error) {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for ListConnections")
	}

	var r0 []model.ConnectionWithAccounts
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.User) ([]model.ConnectionWithAccounts, error)); ok {
		return rf(ctx, user)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.User) []model.ConnectionWithAccounts); ok {
		r0 = rf(ctx, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.ConnectionWithAccounts)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.User) error); ok {
		r1 = rf(ctx, user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_ListConnections_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListConnections'
type Service_ListConnections_Call struct {
	*mock.Call
}

// ListConnections is a helper method to define mock.On call
//   - ctx context.Context
//   - user *model.User
func (_e *Service_Expecter) ListConnections(ctx interface{}, user interface{}) *Service_ListConnections_Call {
	return &Service_ListConnections_Call{Call: _e.mock.On("ListConnections", ctx, user)}
}

func (_c *Service_ListConnections_Call) Run(run func(ctx context.Context, user *model.User)) *Service_ListConnections_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.User))
	})
	return _c
}

func (_c *Service_ListConnections_Call) Return(_a0 []model.ConnectionWithAccounts, _a1 error) *Service_ListConnections_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_ListConnections_Call) RunAndReturn(run func(context.Context, *model.User) ([]model.ConnectionWithAccounts, error)) *Service_ListConnections_Call {
	_c.Call.Return(run)
	return _c
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
