// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
	"time"
)

type Account struct {
	ID                int32          `db:"id"`
	ConnectionID      int32          `db:"connection_id"`
	ProviderAccountID string         `db:"provider_account_id"`
	BankAccountID     sql.NullString `db:"bank_account_id"`
	Name              sql.NullString `db:"name"`
	Type              sql.NullString `db:"type"`
	Currency          sql.NullString `db:"currency"`
	AccountNumber     sql.NullString `db:"account_number"`
	Balance           string         `db:"balance"`
	CreatedAt         time.Time      `db:"created_at"`
	UpdatedAt         time.Time      `db:"updated_at"`
	DeletedAt         sql.NullTime   `db:"deleted_at"`
}

type Connection struct {
	ID                   int32          `db:"id"`
	ProviderUsersID      int32          `db:"provider_users_id"`
	ProviderConnectionID string         `db:"provider_connection_id"`
	ConnectorID          int32          `db:"connector_id"`
	Status               string         `db:"status"`
	RenewConsentBefore   sql.NullTime   `db:"renew_consent_before"`
	ErrorMessage         sql.NullString `db:"error_message"`
	LastSuccessfulSync   sql.NullTime   `db:"last_successful_sync"`
	CreatedAt            time.Time      `db:"created_at"`
	UpdatedAt            time.Time      `db:"updated_at"`
	DeletedAt            sql.NullTime   `db:"deleted_at"`
}

type Connector struct {
	ID                  int32          `db:"id"`
	Name                string         `db:"name"`
	LogoUrl             sql.NullString `db:"logo_url"`
	ProviderConnectorID string         `db:"provider_connector_id"`
	ProviderID          int32          `db:"provider_id"`
	CreatedAt           time.Time      `db:"created_at"`
	UpdatedAt           time.Time      `db:"updated_at"`
	DeletedAt           sql.NullTime   `db:"deleted_at"`
}

type Provider struct {
	ID        int32          `db:"id"`
	Name      string         `db:"name"`
	AccessKey sql.NullString `db:"access_key"`
	Secret    sql.NullString `db:"secret"`
	Enabled   bool           `db:"enabled"`
	CreatedAt time.Time      `db:"created_at"`
	UpdatedAt time.Time      `db:"updated_at"`
	DeletedAt sql.NullTime   `db:"deleted_at"`
}

type ProviderUser struct {
	ID             int32        `db:"id"`
	ProviderID     int32        `db:"provider_id"`
	ProviderUserID string       `db:"provider_user_id"`
	UserID         int32        `db:"user_id"`
	CreatedAt      time.Time    `db:"created_at"`
	UpdatedAt      time.Time    `db:"updated_at"`
	DeletedAt      sql.NullTime `db:"deleted_at"`
}

type RedirectSession struct {
	ID                   string         `db:"id"`
	ProviderConnectionID sql.NullString `db:"provider_connection_id"`
	InternalConnectionID sql.NullInt32  `db:"internal_connection_id"`
	UserID               sql.NullInt32  `db:"user_id"`
	CreatedAt            time.Time      `db:"created_at"`
}

type Transaction struct {
	ID                    int32          `db:"id"`
	AccountID             int32          `db:"account_id"`
	ProviderTransactionID string         `db:"provider_transaction_id"`
	BankTransactionID     sql.NullString `db:"bank_transaction_id"`
	Amount                string         `db:"amount"`
	Currency              string         `db:"currency"`
	Direction             string         `db:"direction"`
	Status                string         `db:"status"`
	OperationAt           time.Time      `db:"operation_at"`
	CounterpartyName      sql.NullString `db:"counterparty_name"`
	CounterpartyAccount   sql.NullString `db:"counterparty_account"`
	Reference             sql.NullString `db:"reference"`
	CreatedAt             time.Time      `db:"created_at"`
	UpdatedAt             time.Time      `db:"updated_at"`
	DeletedAt             sql.NullTime   `db:"deleted_at"`
}

type TransactionEnrichment struct {
	ID                  int32          `db:"id"`
	TransactionID       int32          `db:"transaction_id"`
	Category            sql.NullString `db:"category"`
	Reference           sql.NullString `db:"reference"`
	CounterpartyName    sql.NullString `db:"counterparty_name"`
	CounterpartyLogoUrl sql.NullString `db:"counterparty_logo_url"`
	DeletedAt           sql.NullTime   `db:"deleted_at"`
}

type User struct {
	ID             int32        `db:"id"`
	Username       string       `db:"username"`
	HashedPassword string       `db:"hashed_password"`
	CreatedAt      time.Time    `db:"created_at"`
	UpdatedAt      time.Time    `db:"updated_at"`
	DeletedAt      sql.NullTime `db:"deleted_at"`
}
