// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	CreateCategoryRule(ctx context.Context, arg CreateCategoryRuleParams) (CategoryRule, error)
	CreateConnection(ctx context.Context, arg CreateConnectionParams) (Connection, error)
	CreateProvider(ctx context.Context, arg CreateProviderParams) (Provider, error)
	CreateProviderUser(ctx context.Context, arg CreateProviderUserParams) (ProviderUser, error)
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error)
	CreateTransactionEnrichment(ctx context.Context, arg CreateTransactionEnrichmentParams) (TransactionEnrichment, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAccountByConnectionID(ctx context.Context, connectionID int32) error
	DeleteCategoryByID(ctx context.Context, id int32) error
	DeleteCategoryRuleByCategoryID(ctx context.Context, categoryID int32) error
	DeleteConnectionByID(ctx context.Context, id int32) error
	DeleteTransactionsByConnectionID(ctx context.Context, connectionID int32) error
	DeleteTransactionsEnrichmentsByConnectionID(ctx context.Context, connectionID int32) error
	FindTransactionByAccountIDAndProviderTransactionID(ctx context.Context, arg FindTransactionByAccountIDAndProviderTransactionIDParams) (Transaction, error)
	FuzzySearchConnectorsByName(ctx context.Context, name string) ([]Connector, error)
	GetAccountByConnectionIDAndProviderAccountID(ctx context.Context, arg GetAccountByConnectionIDAndProviderAccountIDParams) (Account, error)
	GetAllCategoriesByUserFromTransactionID(ctx context.Context, id int32) ([]Category, error)
	// after 1000 per user, it is too much, let's ignore them
	GetAllCategoriesByUserID(ctx context.Context, userID sql.NullInt32) ([]Category, error)
	GetAllRulesByUserFromTransactionID(ctx context.Context, id int32) ([]CategoryRule, error)
	GetCategoryRuleByID(ctx context.Context, id int32) (CategoryRule, error)
	GetConnectionByID(ctx context.Context, id int32) (Connection, error)
	GetConnectionByIDAndUserID(ctx context.Context, arg GetConnectionByIDAndUserIDParams) (Connection, error)
	GetConnectionByProviderUserIDAndProviderConnectionID(ctx context.Context, arg GetConnectionByProviderUserIDAndProviderConnectionIDParams) (Connection, error)
	GetConnectorByID(ctx context.Context, id int32) (Connector, error)
	GetImageByID(ctx context.Context, id string) (Image, error)
	GetProviderByID(ctx context.Context, id int32) (Provider, error)
	GetProviderByName(ctx context.Context, name string) (Provider, error)
	GetProviderUserByID(ctx context.Context, id int32) (ProviderUser, error)
	GetProviderUserByProviderIDAndUserID(ctx context.Context, arg GetProviderUserByProviderIDAndUserIDParams) (ProviderUser, error)
	GetRedirectSessionByID(ctx context.Context, id string) (RedirectSession, error)
	GetTransactionByID(ctx context.Context, id int32) (GetTransactionByIDRow, error)
	GetTransactionsByUserIDAndBetweenDates(ctx context.Context, arg GetTransactionsByUserIDAndBetweenDatesParams) ([]GetTransactionsByUserIDAndBetweenDatesRow, error)
	GetTransactionsMinAndMaxDateByUserID(ctx context.Context, userID int32) (GetTransactionsMinAndMaxDateByUserIDRow, error)
	GetUserByID(ctx context.Context, id int32) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetUserIDByTransactionID(ctx context.Context, id int32) (int32, error)
	LikeSearchConnectorsByName(ctx context.Context, name string) ([]Connector, error)
	ListAccountsByConnectionID(ctx context.Context, connectionID int32) ([]Account, error)
	ListAllUserCounterpartiesByTransID(ctx context.Context, id int32) ([]string, error)
	ListConnectionsByUserID(ctx context.Context, userID int32) ([]Connection, error)
	ListConnectionsToSync(ctx context.Context) ([]Connection, error)
	ListProviders(ctx context.Context) ([]Provider, error)
	StoreImage(ctx context.Context, arg StoreImageParams) (Image, error)
	StoreRedirectSessions(ctx context.Context, arg StoreRedirectSessionsParams) error
	UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error)
	UpdateCategoryByIDAndUserID(ctx context.Context, arg UpdateCategoryByIDAndUserIDParams) (Category, error)
	UpdateConnection(ctx context.Context, arg UpdateConnectionParams) (Connection, error)
	UpdateConnectionStatus(ctx context.Context, arg UpdateConnectionStatusParams) (Connection, error)
	UpdateProvider(ctx context.Context, arg UpdateProviderParams) (Provider, error)
	UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (Transaction, error)
	UpdateTransactionEnrichment(ctx context.Context, arg UpdateTransactionEnrichmentParams) (TransactionEnrichment, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpsertConnector(ctx context.Context, arg UpsertConnectorParams) (Connector, error)
}

var _ Querier = (*Queries)(nil)
