// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
	"time"
)

type Connection struct {
	ID                 int32          `db:"id"`
	ProviderUsersID    int32          `db:"provider_users_id"`
	ConnectorID        int32          `db:"connector_id"`
	Status             string         `db:"status"`
	RenewConsentBefore sql.NullTime   `db:"renew_consent_before"`
	ErrorMessage       sql.NullString `db:"error_message"`
	LastSuccessfulSync sql.NullTime   `db:"last_successful_sync"`
	CreatedAt          time.Time      `db:"created_at"`
	UpdatedAt          time.Time      `db:"updated_at"`
	DeletedAt          sql.NullTime   `db:"deleted_at"`
}

type Connector struct {
	ID                  int32          `db:"id"`
	Name                string         `db:"name"`
	LogoUrl             sql.NullString `db:"logo_url"`
	ProviderConnectorID string         `db:"provider_connector_id"`
	ProviderID          int32          `db:"provider_id"`
	CreatedAt           time.Time      `db:"created_at"`
	UpdatedAt           time.Time      `db:"updated_at"`
	DeletedAt           sql.NullTime   `db:"deleted_at"`
}

type Provider struct {
	ID        int32          `db:"id"`
	Name      string         `db:"name"`
	AccessKey sql.NullString `db:"access_key"`
	Secret    sql.NullString `db:"secret"`
	Enabled   bool           `db:"enabled"`
	CreatedAt time.Time      `db:"created_at"`
	UpdatedAt time.Time      `db:"updated_at"`
	DeletedAt sql.NullTime   `db:"deleted_at"`
}

type ProviderUser struct {
	ID             int32        `db:"id"`
	ProviderID     int32        `db:"provider_id"`
	ProviderUserID string       `db:"provider_user_id"`
	UserID         int32        `db:"user_id"`
	CreatedAt      time.Time    `db:"created_at"`
	UpdatedAt      time.Time    `db:"updated_at"`
	DeletedAt      sql.NullTime `db:"deleted_at"`
}

type User struct {
	ID             int32        `db:"id"`
	Username       string       `db:"username"`
	HashedPassword string       `db:"hashed_password"`
	CreatedAt      time.Time    `db:"created_at"`
	UpdatedAt      time.Time    `db:"updated_at"`
	DeletedAt      sql.NullTime `db:"deleted_at"`
}
