name: front
description: "MagniFin front app, used to manage your finances in one place"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  cupertino_icons: ^1.0.8
  go_router: ^14.4.1
  flutter_bloc: ^8.1.6
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  http: ^1.2.2
  toastification: ^2.3.0
  responsive_framework: ^1.5.1
  adaptive_theme: ^3.6.0
  fl_chart: ^0.69.0
  flutter_material_design_icons: ^1.1.7447
  url_launcher: ^6.3.1
  money2: ^5.4.0
  moment_dart: ^2.2.1+beta.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.8.0

flutter:
  generate: true
  uses-material-design: true

flutter_intl:
  enabled: true
