// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import (
	context "context"
	model "magnifin/internal/app/model"

	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

type Service_Expecter struct {
	mock *mock.Mock
}

func (_m *Service) EXPECT() *Service_Expecter {
	return &Service_Expecter{mock: &_m.Mock}
}

// Connect provides a mock function with given fields: ctx, user, connectorID, params
func (_m *Service) Connect(ctx context.Context, user *model.User, connectorID int32, params *model.ConnectParams) (*model.ConnectInstruction, error) {
	ret := _m.Called(ctx, user, connectorID, params)

	if len(ret) == 0 {
		panic("no return value specified for Connect")
	}

	var r0 *model.ConnectInstruction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.User, int32, *model.ConnectParams) (*model.ConnectInstruction, error)); ok {
		return rf(ctx, user, connectorID, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.User, int32, *model.ConnectParams) *model.ConnectInstruction); ok {
		r0 = rf(ctx, user, connectorID, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ConnectInstruction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.User, int32, *model.ConnectParams) error); ok {
		r1 = rf(ctx, user, connectorID, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_Connect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Connect'
type Service_Connect_Call struct {
	*mock.Call
}

// Connect is a helper method to define mock.On call
//   - ctx context.Context
//   - user *model.User
//   - connectorID int32
//   - params *model.ConnectParams
func (_e *Service_Expecter) Connect(ctx interface{}, user interface{}, connectorID interface{}, params interface{}) *Service_Connect_Call {
	return &Service_Connect_Call{Call: _e.mock.On("Connect", ctx, user, connectorID, params)}
}

func (_c *Service_Connect_Call) Run(run func(ctx context.Context, user *model.User, connectorID int32, params *model.ConnectParams)) *Service_Connect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.User), args[2].(int32), args[3].(*model.ConnectParams))
	})
	return _c
}

func (_c *Service_Connect_Call) Return(_a0 *model.ConnectInstruction, _a1 error) *Service_Connect_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_Connect_Call) RunAndReturn(run func(context.Context, *model.User, int32, *model.ConnectParams) (*model.ConnectInstruction, error)) *Service_Connect_Call {
	_c.Call.Return(run)
	return _c
}

// ConnectCallback provides a mock function with given fields: ctx, connectorID, sid, providerConnectionID
func (_m *Service) ConnectCallback(ctx context.Context, connectorID int32, sid string, providerConnectionID *string) error {
	ret := _m.Called(ctx, connectorID, sid, providerConnectionID)

	if len(ret) == 0 {
		panic("no return value specified for ConnectCallback")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int32, string, *string) error); ok {
		r0 = rf(ctx, connectorID, sid, providerConnectionID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Service_ConnectCallback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConnectCallback'
type Service_ConnectCallback_Call struct {
	*mock.Call
}

// ConnectCallback is a helper method to define mock.On call
//   - ctx context.Context
//   - connectorID int32
//   - sid string
//   - providerConnectionID *string
func (_e *Service_Expecter) ConnectCallback(ctx interface{}, connectorID interface{}, sid interface{}, providerConnectionID interface{}) *Service_ConnectCallback_Call {
	return &Service_ConnectCallback_Call{Call: _e.mock.On("ConnectCallback", ctx, connectorID, sid, providerConnectionID)}
}

func (_c *Service_ConnectCallback_Call) Run(run func(ctx context.Context, connectorID int32, sid string, providerConnectionID *string)) *Service_ConnectCallback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32), args[2].(string), args[3].(*string))
	})
	return _c
}

func (_c *Service_ConnectCallback_Call) Return(_a0 error) *Service_ConnectCallback_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_ConnectCallback_Call) RunAndReturn(run func(context.Context, int32, string, *string) error) *Service_ConnectCallback_Call {
	_c.Call.Return(run)
	return _c
}

// SearchByName provides a mock function with given fields: ctx, name
func (_m *Service) SearchByName(ctx context.Context, name string) ([]model.Connector, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for SearchByName")
	}

	var r0 []model.Connector
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]model.Connector, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []model.Connector); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Connector)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_SearchByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchByName'
type Service_SearchByName_Call struct {
	*mock.Call
}

// SearchByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *Service_Expecter) SearchByName(ctx interface{}, name interface{}) *Service_SearchByName_Call {
	return &Service_SearchByName_Call{Call: _e.mock.On("SearchByName", ctx, name)}
}

func (_c *Service_SearchByName_Call) Run(run func(ctx context.Context, name string)) *Service_SearchByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Service_SearchByName_Call) Return(_a0 []model.Connector, _a1 error) *Service_SearchByName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_SearchByName_Call) RunAndReturn(run func(context.Context, string) ([]model.Connector, error)) *Service_SearchByName_Call {
	_c.Call.Return(run)
	return _c
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
