// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import (
	context "context"
	model "magnifin/internal/app/model"

	mock "github.com/stretchr/testify/mock"
)

// AccountsRepository is an autogenerated mock type for the AccountsRepository type
type AccountsRepository struct {
	mock.Mock
}

type AccountsRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *AccountsRepository) EXPECT() *AccountsRepository_Expecter {
	return &AccountsRepository_Expecter{mock: &_m.Mock}
}

// ListByConnection provides a mock function with given fields: ctx, connectionID
func (_m *AccountsRepository) ListByConnection(ctx context.Context, connectionID int32) ([]model.Account, error) {
	ret := _m.Called(ctx, connectionID)

	if len(ret) == 0 {
		panic("no return value specified for ListByConnection")
	}

	var r0 []model.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) ([]model.Account, error)); ok {
		return rf(ctx, connectionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32) []model.Account); ok {
		r0 = rf(ctx, connectionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Account)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = rf(ctx, connectionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AccountsRepository_ListByConnection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByConnection'
type AccountsRepository_ListByConnection_Call struct {
	*mock.Call
}

// ListByConnection is a helper method to define mock.On call
//   - ctx context.Context
//   - connectionID int32
func (_e *AccountsRepository_Expecter) ListByConnection(ctx interface{}, connectionID interface{}) *AccountsRepository_ListByConnection_Call {
	return &AccountsRepository_ListByConnection_Call{Call: _e.mock.On("ListByConnection", ctx, connectionID)}
}

func (_c *AccountsRepository_ListByConnection_Call) Run(run func(ctx context.Context, connectionID int32)) *AccountsRepository_ListByConnection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *AccountsRepository_ListByConnection_Call) Return(_a0 []model.Account, _a1 error) *AccountsRepository_ListByConnection_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AccountsRepository_ListByConnection_Call) RunAndReturn(run func(context.Context, int32) ([]model.Account, error)) *AccountsRepository_ListByConnection_Call {
	_c.Call.Return(run)
	return _c
}

// NewAccountsRepository creates a new instance of AccountsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAccountsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *AccountsRepository {
	mock := &AccountsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
