// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import (
	context "context"
	model "magnifin/internal/app/model"

	mock "github.com/stretchr/testify/mock"
)

// ConnectorsRepository is an autogenerated mock type for the ConnectorsRepository type
type ConnectorsRepository struct {
	mock.Mock
}

type ConnectorsRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *ConnectorsRepository) EXPECT() *ConnectorsRepository_Expecter {
	return &ConnectorsRepository_Expecter{mock: &_m.Mock}
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *ConnectorsRepository) GetByID(ctx context.Context, id int32) (*model.Connector, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *model.Connector
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) (*model.Connector, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32) *model.Connector); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Connector)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ConnectorsRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type ConnectorsRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
func (_e *ConnectorsRepository_Expecter) GetByID(ctx interface{}, id interface{}) *ConnectorsRepository_GetByID_Call {
	return &ConnectorsRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *ConnectorsRepository_GetByID_Call) Run(run func(ctx context.Context, id int32)) *ConnectorsRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *ConnectorsRepository_GetByID_Call) Return(_a0 *model.Connector, _a1 error) *ConnectorsRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ConnectorsRepository_GetByID_Call) RunAndReturn(run func(context.Context, int32) (*model.Connector, error)) *ConnectorsRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewConnectorsRepository creates a new instance of ConnectorsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewConnectorsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ConnectorsRepository {
	mock := &ConnectorsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
