// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import (
	context "context"
	model "magnifin/internal/app/model"

	mock "github.com/stretchr/testify/mock"
)

// ConnectionsRepository is an autogenerated mock type for the ConnectionsRepository type
type ConnectionsRepository struct {
	mock.Mock
}

type ConnectionsRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *ConnectionsRepository) EXPECT() *ConnectionsRepository_Expecter {
	return &ConnectionsRepository_Expecter{mock: &_m.Mock}
}

// ListActiveByUser provides a mock function with given fields: ctx, user
func (_m *ConnectionsRepository) ListActiveByUser(ctx context.Context, user *model.User) ([]model.Connection, error) {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for ListActiveByUser")
	}

	var r0 []model.Connection
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.User) ([]model.Connection, error)); ok {
		return rf(ctx, user)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.User) []model.Connection); ok {
		r0 = rf(ctx, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Connection)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.User) error); ok {
		r1 = rf(ctx, user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ConnectionsRepository_ListActiveByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListActiveByUser'
type ConnectionsRepository_ListActiveByUser_Call struct {
	*mock.Call
}

// ListActiveByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - user *model.User
func (_e *ConnectionsRepository_Expecter) ListActiveByUser(ctx interface{}, user interface{}) *ConnectionsRepository_ListActiveByUser_Call {
	return &ConnectionsRepository_ListActiveByUser_Call{Call: _e.mock.On("ListActiveByUser", ctx, user)}
}

func (_c *ConnectionsRepository_ListActiveByUser_Call) Run(run func(ctx context.Context, user *model.User)) *ConnectionsRepository_ListActiveByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.User))
	})
	return _c
}

func (_c *ConnectionsRepository_ListActiveByUser_Call) Return(_a0 []model.Connection, _a1 error) *ConnectionsRepository_ListActiveByUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ConnectionsRepository_ListActiveByUser_Call) RunAndReturn(run func(context.Context, *model.User) ([]model.Connection, error)) *ConnectionsRepository_ListActiveByUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewConnectionsRepository creates a new instance of ConnectionsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewConnectionsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ConnectionsRepository {
	mock := &ConnectionsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
