// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import (
	context "context"
	model "magnifin/internal/app/model"

	mock "github.com/stretchr/testify/mock"
)

// ProviderRepository is an autogenerated mock type for the ProviderRepository type
type ProviderRepository struct {
	mock.Mock
}

type ProviderRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *ProviderRepository) EXPECT() *ProviderRepository_Expecter {
	return &ProviderRepository_Expecter{mock: &_m.Mock}
}

// GetByName provides a mock function with given fields: ctx, name
func (_m *ProviderRepository) GetByName(ctx context.Context, name string) (*model.Provider, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetByName")
	}

	var r0 *model.Provider
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Provider, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Provider); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Provider)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ProviderRepository_GetByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByName'
type ProviderRepository_GetByName_Call struct {
	*mock.Call
}

// GetByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *ProviderRepository_Expecter) GetByName(ctx interface{}, name interface{}) *ProviderRepository_GetByName_Call {
	return &ProviderRepository_GetByName_Call{Call: _e.mock.On("GetByName", ctx, name)}
}

func (_c *ProviderRepository_GetByName_Call) Run(run func(ctx context.Context, name string)) *ProviderRepository_GetByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ProviderRepository_GetByName_Call) Return(_a0 *model.Provider, _a1 error) *ProviderRepository_GetByName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ProviderRepository_GetByName_Call) RunAndReturn(run func(context.Context, string) (*model.Provider, error)) *ProviderRepository_GetByName_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx
func (_m *ProviderRepository) List(ctx context.Context) ([]model.Provider, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []model.Provider
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]model.Provider, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []model.Provider); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Provider)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ProviderRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type ProviderRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *ProviderRepository_Expecter) List(ctx interface{}) *ProviderRepository_List_Call {
	return &ProviderRepository_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *ProviderRepository_List_Call) Run(run func(ctx context.Context)) *ProviderRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *ProviderRepository_List_Call) Return(_a0 []model.Provider, _a1 error) *ProviderRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ProviderRepository_List_Call) RunAndReturn(run func(context.Context) ([]model.Provider, error)) *ProviderRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, provider
func (_m *ProviderRepository) Update(ctx context.Context, provider *model.Provider) (*model.Provider, error) {
	ret := _m.Called(ctx, provider)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *model.Provider
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Provider) (*model.Provider, error)); ok {
		return rf(ctx, provider)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.Provider) *model.Provider); ok {
		r0 = rf(ctx, provider)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Provider)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.Provider) error); ok {
		r1 = rf(ctx, provider)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ProviderRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type ProviderRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - provider *model.Provider
func (_e *ProviderRepository_Expecter) Update(ctx interface{}, provider interface{}) *ProviderRepository_Update_Call {
	return &ProviderRepository_Update_Call{Call: _e.mock.On("Update", ctx, provider)}
}

func (_c *ProviderRepository_Update_Call) Run(run func(ctx context.Context, provider *model.Provider)) *ProviderRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Provider))
	})
	return _c
}

func (_c *ProviderRepository_Update_Call) Return(_a0 *model.Provider, _a1 error) *ProviderRepository_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ProviderRepository_Update_Call) RunAndReturn(run func(context.Context, *model.Provider) (*model.Provider, error)) *ProviderRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewProviderRepository creates a new instance of ProviderRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProviderRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProviderRepository {
	mock := &ProviderRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
