// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import (
	context "context"
	database "magnifin/internal/infra/database"

	mock "github.com/stretchr/testify/mock"

	sql "database/sql"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

type Service_Expecter struct {
	mock *mock.Mock
}

func (_m *Service) EXPECT() *Service_Expecter {
	return &Service_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with given fields:
func (_m *Service) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Service_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type Service_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *Service_Expecter) Close() *Service_Close_Call {
	return &Service_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *Service_Close_Call) Run(run func()) *Service_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Service_Close_Call) Return(_a0 error) *Service_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_Close_Call) RunAndReturn(run func() error) *Service_Close_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUser provides a mock function with given fields: ctx, arg
func (_m *Service) CreateUser(ctx context.Context, arg database.CreateUserParams) (database.User, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 database.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, database.CreateUserParams) (database.User, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, database.CreateUserParams) database.User); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(database.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, database.CreateUserParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type Service_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - arg database.CreateUserParams
func (_e *Service_Expecter) CreateUser(ctx interface{}, arg interface{}) *Service_CreateUser_Call {
	return &Service_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, arg)}
}

func (_c *Service_CreateUser_Call) Run(run func(ctx context.Context, arg database.CreateUserParams)) *Service_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(database.CreateUserParams))
	})
	return _c
}

func (_c *Service_CreateUser_Call) Return(_a0 database.User, _a1 error) *Service_CreateUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_CreateUser_Call) RunAndReturn(run func(context.Context, database.CreateUserParams) (database.User, error)) *Service_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// Driver provides a mock function with given fields:
func (_m *Service) Driver() *sql.DB {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Driver")
	}

	var r0 *sql.DB
	if rf, ok := ret.Get(0).(func() *sql.DB); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.DB)
		}
	}

	return r0
}

// Service_Driver_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Driver'
type Service_Driver_Call struct {
	*mock.Call
}

// Driver is a helper method to define mock.On call
func (_e *Service_Expecter) Driver() *Service_Driver_Call {
	return &Service_Driver_Call{Call: _e.mock.On("Driver")}
}

func (_c *Service_Driver_Call) Run(run func()) *Service_Driver_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Service_Driver_Call) Return(_a0 *sql.DB) *Service_Driver_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_Driver_Call) RunAndReturn(run func() *sql.DB) *Service_Driver_Call {
	_c.Call.Return(run)
	return _c
}

// GetProviderByID provides a mock function with given fields: ctx, id
func (_m *Service) GetProviderByID(ctx context.Context, id int32) (database.Provider, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetProviderByID")
	}

	var r0 database.Provider
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) (database.Provider, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32) database.Provider); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(database.Provider)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_GetProviderByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProviderByID'
type Service_GetProviderByID_Call struct {
	*mock.Call
}

// GetProviderByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
func (_e *Service_Expecter) GetProviderByID(ctx interface{}, id interface{}) *Service_GetProviderByID_Call {
	return &Service_GetProviderByID_Call{Call: _e.mock.On("GetProviderByID", ctx, id)}
}

func (_c *Service_GetProviderByID_Call) Run(run func(ctx context.Context, id int32)) *Service_GetProviderByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *Service_GetProviderByID_Call) Return(_a0 database.Provider, _a1 error) *Service_GetProviderByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_GetProviderByID_Call) RunAndReturn(run func(context.Context, int32) (database.Provider, error)) *Service_GetProviderByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetProviderByName provides a mock function with given fields: ctx, name
func (_m *Service) GetProviderByName(ctx context.Context, name string) (database.Provider, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetProviderByName")
	}

	var r0 database.Provider
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (database.Provider, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) database.Provider); ok {
		r0 = rf(ctx, name)
	} else {
		r0 = ret.Get(0).(database.Provider)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_GetProviderByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProviderByName'
type Service_GetProviderByName_Call struct {
	*mock.Call
}

// GetProviderByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *Service_Expecter) GetProviderByName(ctx interface{}, name interface{}) *Service_GetProviderByName_Call {
	return &Service_GetProviderByName_Call{Call: _e.mock.On("GetProviderByName", ctx, name)}
}

func (_c *Service_GetProviderByName_Call) Run(run func(ctx context.Context, name string)) *Service_GetProviderByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Service_GetProviderByName_Call) Return(_a0 database.Provider, _a1 error) *Service_GetProviderByName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_GetProviderByName_Call) RunAndReturn(run func(context.Context, string) (database.Provider, error)) *Service_GetProviderByName_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByID provides a mock function with given fields: ctx, id
func (_m *Service) GetUserByID(ctx context.Context, id int32) (database.User, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByID")
	}

	var r0 database.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) (database.User, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32) database.User); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(database.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_GetUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByID'
type Service_GetUserByID_Call struct {
	*mock.Call
}

// GetUserByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
func (_e *Service_Expecter) GetUserByID(ctx interface{}, id interface{}) *Service_GetUserByID_Call {
	return &Service_GetUserByID_Call{Call: _e.mock.On("GetUserByID", ctx, id)}
}

func (_c *Service_GetUserByID_Call) Run(run func(ctx context.Context, id int32)) *Service_GetUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *Service_GetUserByID_Call) Return(_a0 database.User, _a1 error) *Service_GetUserByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_GetUserByID_Call) RunAndReturn(run func(context.Context, int32) (database.User, error)) *Service_GetUserByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByUsernameAndHashedPassword provides a mock function with given fields: ctx, arg
func (_m *Service) GetUserByUsernameAndHashedPassword(ctx context.Context, arg database.GetUserByUsernameAndHashedPasswordParams) (database.User, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByUsernameAndHashedPassword")
	}

	var r0 database.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, database.GetUserByUsernameAndHashedPasswordParams) (database.User, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, database.GetUserByUsernameAndHashedPasswordParams) database.User); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(database.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, database.GetUserByUsernameAndHashedPasswordParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_GetUserByUsernameAndHashedPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByUsernameAndHashedPassword'
type Service_GetUserByUsernameAndHashedPassword_Call struct {
	*mock.Call
}

// GetUserByUsernameAndHashedPassword is a helper method to define mock.On call
//   - ctx context.Context
//   - arg database.GetUserByUsernameAndHashedPasswordParams
func (_e *Service_Expecter) GetUserByUsernameAndHashedPassword(ctx interface{}, arg interface{}) *Service_GetUserByUsernameAndHashedPassword_Call {
	return &Service_GetUserByUsernameAndHashedPassword_Call{Call: _e.mock.On("GetUserByUsernameAndHashedPassword", ctx, arg)}
}

func (_c *Service_GetUserByUsernameAndHashedPassword_Call) Run(run func(ctx context.Context, arg database.GetUserByUsernameAndHashedPasswordParams)) *Service_GetUserByUsernameAndHashedPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(database.GetUserByUsernameAndHashedPasswordParams))
	})
	return _c
}

func (_c *Service_GetUserByUsernameAndHashedPassword_Call) Return(_a0 database.User, _a1 error) *Service_GetUserByUsernameAndHashedPassword_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_GetUserByUsernameAndHashedPassword_Call) RunAndReturn(run func(context.Context, database.GetUserByUsernameAndHashedPasswordParams) (database.User, error)) *Service_GetUserByUsernameAndHashedPassword_Call {
	_c.Call.Return(run)
	return _c
}

// Health provides a mock function with given fields:
func (_m *Service) Health() map[string]string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Health")
	}

	var r0 map[string]string
	if rf, ok := ret.Get(0).(func() map[string]string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}

	return r0
}

// Service_Health_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Health'
type Service_Health_Call struct {
	*mock.Call
}

// Health is a helper method to define mock.On call
func (_e *Service_Expecter) Health() *Service_Health_Call {
	return &Service_Health_Call{Call: _e.mock.On("Health")}
}

func (_c *Service_Health_Call) Run(run func()) *Service_Health_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Service_Health_Call) Return(_a0 map[string]string) *Service_Health_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_Health_Call) RunAndReturn(run func() map[string]string) *Service_Health_Call {
	_c.Call.Return(run)
	return _c
}

// ListProviders provides a mock function with given fields: ctx
func (_m *Service) ListProviders(ctx context.Context) ([]database.Provider, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListProviders")
	}

	var r0 []database.Provider
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]database.Provider, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []database.Provider); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.Provider)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_ListProviders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListProviders'
type Service_ListProviders_Call struct {
	*mock.Call
}

// ListProviders is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Service_Expecter) ListProviders(ctx interface{}) *Service_ListProviders_Call {
	return &Service_ListProviders_Call{Call: _e.mock.On("ListProviders", ctx)}
}

func (_c *Service_ListProviders_Call) Run(run func(ctx context.Context)) *Service_ListProviders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Service_ListProviders_Call) Return(_a0 []database.Provider, _a1 error) *Service_ListProviders_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_ListProviders_Call) RunAndReturn(run func(context.Context) ([]database.Provider, error)) *Service_ListProviders_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateProvider provides a mock function with given fields: ctx, arg
func (_m *Service) UpdateProvider(ctx context.Context, arg database.UpdateProviderParams) (database.Provider, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProvider")
	}

	var r0 database.Provider
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, database.UpdateProviderParams) (database.Provider, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, database.UpdateProviderParams) database.Provider); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(database.Provider)
	}

	if rf, ok := ret.Get(1).(func(context.Context, database.UpdateProviderParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_UpdateProvider_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateProvider'
type Service_UpdateProvider_Call struct {
	*mock.Call
}

// UpdateProvider is a helper method to define mock.On call
//   - ctx context.Context
//   - arg database.UpdateProviderParams
func (_e *Service_Expecter) UpdateProvider(ctx interface{}, arg interface{}) *Service_UpdateProvider_Call {
	return &Service_UpdateProvider_Call{Call: _e.mock.On("UpdateProvider", ctx, arg)}
}

func (_c *Service_UpdateProvider_Call) Run(run func(ctx context.Context, arg database.UpdateProviderParams)) *Service_UpdateProvider_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(database.UpdateProviderParams))
	})
	return _c
}

func (_c *Service_UpdateProvider_Call) Return(_a0 database.Provider, _a1 error) *Service_UpdateProvider_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_UpdateProvider_Call) RunAndReturn(run func(context.Context, database.UpdateProviderParams) (database.Provider, error)) *Service_UpdateProvider_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUser provides a mock function with given fields: ctx, arg
func (_m *Service) UpdateUser(ctx context.Context, arg database.UpdateUserParams) (database.User, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUser")
	}

	var r0 database.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, database.UpdateUserParams) (database.User, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, database.UpdateUserParams) database.User); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(database.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, database.UpdateUserParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_UpdateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUser'
type Service_UpdateUser_Call struct {
	*mock.Call
}

// UpdateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - arg database.UpdateUserParams
func (_e *Service_Expecter) UpdateUser(ctx interface{}, arg interface{}) *Service_UpdateUser_Call {
	return &Service_UpdateUser_Call{Call: _e.mock.On("UpdateUser", ctx, arg)}
}

func (_c *Service_UpdateUser_Call) Run(run func(ctx context.Context, arg database.UpdateUserParams)) *Service_UpdateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(database.UpdateUserParams))
	})
	return _c
}

func (_c *Service_UpdateUser_Call) Return(_a0 database.User, _a1 error) *Service_UpdateUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_UpdateUser_Call) RunAndReturn(run func(context.Context, database.UpdateUserParams) (database.User, error)) *Service_UpdateUser_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertConnector provides a mock function with given fields: ctx, arg
func (_m *Service) UpsertConnector(ctx context.Context, arg database.UpsertConnectorParams) (database.Connector, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpsertConnector")
	}

	var r0 database.Connector
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, database.UpsertConnectorParams) (database.Connector, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, database.UpsertConnectorParams) database.Connector); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(database.Connector)
	}

	if rf, ok := ret.Get(1).(func(context.Context, database.UpsertConnectorParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Service_UpsertConnector_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertConnector'
type Service_UpsertConnector_Call struct {
	*mock.Call
}

// UpsertConnector is a helper method to define mock.On call
//   - ctx context.Context
//   - arg database.UpsertConnectorParams
func (_e *Service_Expecter) UpsertConnector(ctx interface{}, arg interface{}) *Service_UpsertConnector_Call {
	return &Service_UpsertConnector_Call{Call: _e.mock.On("UpsertConnector", ctx, arg)}
}

func (_c *Service_UpsertConnector_Call) Run(run func(ctx context.Context, arg database.UpsertConnectorParams)) *Service_UpsertConnector_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(database.UpsertConnectorParams))
	})
	return _c
}

func (_c *Service_UpsertConnector_Call) Return(_a0 database.Connector, _a1 error) *Service_UpsertConnector_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Service_UpsertConnector_Call) RunAndReturn(run func(context.Context, database.UpsertConnectorParams) (database.Connector, error)) *Service_UpsertConnector_Call {
	_c.Call.Return(run)
	return _c
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
